#!/bin/bash

echo "Setting up Client Documentation Wiki System..."
echo ""
echo "This script will guide you through setting up the wiki system."
echo ""
echo "1. First, run the SQL migration in your Supabase SQL editor:"
echo "   - Open your Supabase project dashboard"
echo "   - Go to SQL Editor"
echo "   - Copy and paste the contents of 'setup_client_wiki.sql'"
echo "   - Run the migration"
echo ""
echo "2. The migration will create the following tables:"
echo "   - client_documents (main documents storage)"
echo "   - document_versions (version history)"
echo "   - document_permissions (access control)"
echo "   - document_audit_logs (audit trail)"
echo ""
echo "3. Security features included:"
echo "   - Row Level Security (RLS) policies"
echo "   - Document-level permissions"
echo "   - Sensitive content encryption support"
echo "   - Audit logging"
echo ""
echo "4. After running the migration, you can:"
echo "   - Use the EnhancedClients page for the new UI"
echo "   - Create and manage client documentation"
echo "   - Set document permissions and sensitivity levels"
echo "   - Track document versions and changes"
echo ""
echo "Files created:"
echo "   - setup_client_wiki.sql (database migration)"
echo "   - src/hooks/useClientDocuments.ts (React hooks)"
echo "   - src/components/wiki/DocumentEditor.tsx (Tiptap editor)"
echo "   - src/components/wiki/DocumentRenderer.tsx (Markdown renderer)"
echo "   - src/components/wiki/DocumentList.tsx (Document list UI)"
echo "   - src/components/wiki/ClientDocumentation.tsx (Main component)"
echo "   - src/pages/EnhancedClients.tsx (Enhanced clients page with docs)"
echo ""
echo "Ready to use! 🚀"
